### PR TITLE
 ux changes; surpress logging of private key

### PR DESCRIPTION
**Pull request by chikeichan**
Hey @rithvikvibhu !

Just reviewed your PR and made some changes. Overall great work! It's very thorough and thoughtful.

I have made the following (mostly UX) changes, please review and let me know if you have any questions!
- redesign private key textarea to surface "Select File" button without additional clicks
- disable autoComplete and autoCorrect on textarea. just general security practice when using input/textarea that contains sensitive plain text. (not needed for input type=password)
- add secondary cta on all steps to either "Go Back" or "Start Over" if proofs failed
- move manual/wizard toggle to secondary CTA
- surpress logging of private key. you wouldn't have known about this one, but ipc messages are logged, and we want to sanitize sensitive data before logging.

Screen Shot 2021-05-17 at 11 02 36 PM
Screen Shot 2021-05-17 at 11 02 28 PM
Screen Shot 2021-05-17 at 11 02 19 PM
Screen Shot 2021-05-17 at 11 02 14 PM

### CODE REVIEW

**Comment by rithvikvibhu** [comment]
Oh cool thanks, will keep those things in mind for future PRs (logging, inputs, ui).

About the file select, can't test it right now, does it handle binary (unarmored) pgp keys? Does the textarea update with garbage-looking value? I see the `value={privKey}` is still there.

**Comment by chikeichan** [comment]
oh it likely doesn't - let me restore the `isFile` param then, but i will keep the garbage-looking value for UI consistency

**Comment by chikeichan** [comment]
@rithvikvibhu added back file params. Also 2 stylistic nits 😅  - don't forget semi-colons, and try to avoid if-statement without parens. It's important to maintain style consistency as codebase gets larger. Let's add eslint and have linter autofix these going forward.

**Comment by rithvikvibhu** [comment]
I have prettier + eslint, with lint on save set up but some files (like ProofModal) have a lot of changes so had to manually "save without formatting" on that file. The other ones like step*.js follow I think.

Will check for semicolons and stuff on manual saves. And yeah an eslint config would help a lot, but will be a huge commit and be a problem for existing PRs and others' forks/branches.

**Comment by chikeichan** [comment]
Let's do the eslint + autofix huge commit as a separate PR after we clear all the current open ones then

**Pull request merged**
